# Generated by Django 5.1.4 on 2025-07-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_variant_size'),
        ('variant_size_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant_size_app.variantsize'),
        ),
    ]
