# Generated by Django 5.1.4 on 2025-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0007_alter_category_category_unit'),
        ('variant_size_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsize',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('mg', 'Milligram'), ('ml', 'Milliliter')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='variantsize',
            name='size_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='variantsize',
            unique_together={('size_name', 'unit', 'category')},
        ),
    ]
