# Generated by Django 5.1.4 on 2025-07-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_size_app', '0002_variantsize_unit_alter_variantsize_size_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='unit',
            field=models.CharField(choices=[('ml', 'Milligram'), ('bottle', 'Bottle'), ('box', 'Box')], default='g', max_length=10),
        ),
    ]
