# Generated by Django 5.1.4 on 2025-07-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0007_alter_referral_user_and_more'),
    ]

    operations = [
    ]
