# Generated by Django 5.1.4 on 2025-07-16 13:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0009_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_address', models.BooleanField(default=False)),
                ('full_name', models.CharField(default='Not Added', max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=30, null=True)),
                ('address_type', models.CharField(default='Home', max_length=10)),
                ('accessible', models.CharField(default='Not Added', max_length=50)),
                ('area', models.CharField(default='Not Added', max_length=50)),
                ('city', models.CharField(default='Not Added', max_length=50)),
                ('pincode', models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits', regex='^\\d{6}$')])),
                ('post_office', models.CharField(default='Not Added', max_length=40)),
                ('state', models.CharField(default='Not Added', max_length=40)),
                ('phone_no', models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('alternative_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
