# Generated by Django 5.1.4 on 2025-07-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0025_alter_order_address'),
        ('user_profile_app', '0010_remove_userprofile_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
